---
apiVersion: v2
description: RomM (Rom Manager) is a web based retro roms manager integrated with IGDB.
name: romm
type: application
home: https://norrstuga.github.io/romm/
icon: https://raw.githubusercontent.com/CrystalNET-org/helm-romm/main/chart/icon.png
version: 0.4.1
# renovate: image=zurdi15/romm
appVersion: "3.10.2"
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: psych0d0g
    email: h@xx0r.eu
  - name: zshel
    email: romm@norrstuga.se
sources:
  - https://github.com/rommapp/romm
  - https://github.com/CrystalNET-org/helm-romm
  - https://github.com/norrstuga/helm-romm
dependencies:
  - name: redis
    version: ~18
    repository: https://charts.bitnami.com/bitnami
    alias: redis
    condition: redis.enabled
  - name: mariadb
    version: ~15
    repository: https://charts.bitnami.com/bitnami
    alias: mariadb
    condition: mariadb.enabled
