{{- if .Values.mediaVolume.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "romm.fullname" $ }}-mediavol-{{ .Values.mediaVolume.name }}
  labels:
    {{- include "romm.labels" $ | nindent 4 }}
    {{- with $.Values.global.commonLabels }}{{ toYaml . | nindent 4 }}{{ end }}
spec:
  storageClassName: {{ .Values.mediaVolume.volumeSpec.storageClassName | quote }}
  {{- if not .Values.mediaVolume.pvcOnly -}}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" $ | nindent 6 }}
      romm-volume: {{ .Values.mediaVolume.name }}
  {{- end }}
  accessModes: {{ toYaml .Values.mediaVolume.volumeSpec.accessModes | nindent 4 }}
  resources:
    requests: {{ toYaml .Values.mediaVolume.volumeSpec.capacity | nindent 6 }}
{{- if not .Values.mediaVolume.pvcOnly -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "romm.fullname" $ }}-mediavol-{{ .Values.mediaVolume.name }}
  labels:
    {{- include "romm.labels" $ | nindent 4 }}
    {{- with $.Values.global.commonLabels }}{{ toYaml . | nindent 4 }}{{ end }}
    romm-volume: {{ .Values.mediaVolume.name }}
spec: {{ toYaml .Values.mediaVolume.volumeSpec | nindent 2 }}
{{- end }}
{{- end }}